#!/bin/bash
# 変数定義
array_communicate_stub=(sqlplus rman)
array_simple_stub=(db_check)
tmp_com_stub=template_communicate_stub
tmp_simple_stub=template_simple_stub

# setup.sh で作成したスクリプトを削除するモード
# 引数にcleanを与えられたときのみ実行
if [ "$1" == "clean" ]; then
    echo "INFO: clean all scripts generated by this script"
    # template_communicate_stubを元にするスタブの削除
    for item in ${array_communicate_stub[@]}; do
        if [ -e ./${item} ]; then
            rm ./${item}
            echo "INFO: remove ${item}"
        fi
        if [ -e ./${item}.dat ]; then
            rm ./${item}.dat
            echo "INFO: remove ${item}.dat"
        fi
    done

    # template_simple_stubを元にするスタブの作成
    for item in ${array_simple_stub[@]}; do
        if [ -e ./${item}.sh ]; then
            rm ./${item}.sh
            echo "INFO: remove ${item}.sh"
        fi
        if [ -e ./${item}.dat ]; then
            rm ./${item}.dat
            echo "INFO: remove ${item}.dat"
        fi
    done
    cd ..
    rm ./${tmp_com_stub}
    echo "INFO: all done!"
    exit 0
fi

# 引数がない場合は以下を実行する
# テスト実行時の準備処理を記載しておく
echo "INFO: prepare stub script"

if [ ! -e ../${tmp_com_stub} ]; then
    current_dir=$(pwd)
    cd ..
    make
    cd $current_dir
fi

# template_communicate_stubを元にするスタブの作成
for item in ${array_communicate_stub[@]}; do
    cp -pr ../${tmp_com_stub} ./${item}
    cp -pr ../${tmp_com_stub}.dat ./${item}.dat
done

# template_simple_stubを元にするスタブの作成
for item in ${array_simple_stub[@]}; do
    cp -pr ../${tmp_simple_stub}.sh ./${item}.sh
    cp -pr ../${tmp_simple_stub}.dat ./${item}.dat
done

echo "done prepare!"
# export PATH=./:$PATH
