#!/bin/bash
# variable declaration
array_communicate_stub=(sqlplus rman)
array_simple_stub=(db_check)
tmp_com_stub=template_communicate_stub
tmp_simple_stub=template_simple_stub

# mode to delete the script created by setup.sh
# execute only when clean is given as an argument
if [ "$1" == "clean" ]; then
    echo "INFO: clean all scripts generated by this script"
    # remove stubs based on template_communicate_stub
    for item in ${array_communicate_stub[@]}; do
        if [ -e ./${item} ]; then
            rm ./${item}
            echo "INFO: remove ${item}"
        fi
        if [ -e ./${item}.dat ]; then
            rm ./${item}.dat
            echo "INFO: remove ${item}.dat"
        fi
    done

    # creating a stub based on template_simple_stub
    for item in ${array_simple_stub[@]}; do
        if [ -e ./${item}.sh ]; then
            rm ./${item}.sh
            echo "INFO: remove ${item}.sh"
        fi
        if [ -e ./${item}.dat ]; then
            rm ./${item}.dat
            echo "INFO: remove ${item}.dat"
        fi
    done
    cd ..
    rm ./${tmp_com_stub}
    echo "INFO: all done!"
    exit 0
fi

# If there are no arguments, do the following
# Describe the preparation process when executing the test
echo "INFO: prepare stub script"

if [ ! -e ../${tmp_com_stub} ]; then
    current_dir=$(pwd)
    cd ..
    make
    cd $current_dir
fi

# Creating a stub based on template_communicate_stub
for item in ${array_communicate_stub[@]}; do
    cp -pr ../${tmp_com_stub} ./${item}
    cp -pr ../${tmp_com_stub}.dat ./${item}.dat
done

# Creating a stub based on template_simple_stub
for item in ${array_simple_stub[@]}; do
    cp -pr ../${tmp_simple_stub}.sh ./${item}.sh
    cp -pr ../${tmp_simple_stub}.dat ./${item}.dat
done

echo "done prepare!"
